import { FormFieldDefinition, ModuleDefinition, WorkspaceViewDefinition } from '../../core/models';

const option = (value: string) => ({ label: value.replace(/([a-z])([A-Z])/g, '$1 $2'), value });
const options = (...values: string[]) => values.map(option);
const currencies = options('USD', 'SGD', 'INR', 'EUR', 'GBP');
const employees = {
  optionsEndpoint: '/employees?page=1&pageSize=200',
  optionsShape: 'paged' as const,
  optionLabel: 'fullName',
  optionValue: 'id',
};
const departments = {
  optionsEndpoint: '/organization/departments',
  optionLabel: 'name',
  optionValue: 'id',
};
const locations = {
  optionsEndpoint: '/organization/locations',
  optionLabel: 'name',
  optionValue: 'id',
};
const leaveTypes = { optionsEndpoint: '/leave/types', optionLabel: 'name', optionValue: 'id' };
const roles = { optionsEndpoint: '/identity/roles', optionLabel: 'name', optionValue: 'id' };

const employeeField = (
  key = 'employeeId',
  label = 'Employee',
  required = true,
): FormFieldDefinition => ({ key, label, type: 'select', required, ...employees });
const versionField: FormFieldDefinition = {
  key: 'version',
  label: 'Record version',
  type: 'number',
  required: true,
  sourceKey: 'version',
  help: 'Used to prevent overwriting a newer update.',
};
const approveFields: FormFieldDefinition[] = [
  {
    key: 'approve',
    label: 'Decision',
    type: 'select',
    required: true,
    options: [
      { label: 'Approve', value: true },
      { label: 'Reject', value: false },
    ],
  },
  versionField,
];

const metrics = (items: [string, string, string, 'blue' | 'green' | 'amber' | 'violet'][]) =>
  items.map(([label, value, trend, tone]) => ({ label, value, trend, tone }));

const organizationViews: WorkspaceViewDefinition[] = [
  {
    label: 'Departments',
    icon: 'account_tree',
    endpoint: '/organization/departments',
    listShape: 'array',
    createEndpoint: '/organization/departments',
    createLabel: 'Add department',
    columns: [
      { key: 'name', label: 'Department' },
      { key: 'code', label: 'Code' },
      { key: 'parentDepartmentId', label: 'Parent department' },
      { key: 'headEmployeeId', label: 'Head' },
      { key: 'isActive', label: 'Status', type: 'status' },
    ],
    fields: [
      { key: 'name', label: 'Department name', type: 'text', required: true },
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'parentDepartmentId', label: 'Parent department', type: 'select', ...departments },
    ],
  },
  {
    label: 'Designations',
    icon: 'workspace_premium',
    endpoint: '/organization/designations',
    listShape: 'array',
    createEndpoint: '/organization/designations',
    createLabel: 'Add designation',
    columns: [
      { key: 'name', label: 'Designation' },
      { key: 'code', label: 'Code' },
      { key: 'level', label: 'Level', type: 'number' },
      { key: 'description', label: 'Description' },
      { key: 'isActive', label: 'Status', type: 'status' },
    ],
    fields: [
      { key: 'name', label: 'Designation name', type: 'text', required: true },
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'level', label: 'Level', type: 'number', required: true, min: 1 },
      { key: 'description', label: 'Description', type: 'textarea' },
    ],
  },
  {
    label: 'Locations',
    icon: 'location_on',
    endpoint: '/organization/locations',
    listShape: 'array',
    createEndpoint: '/organization/locations',
    createLabel: 'Add location',
    columns: [
      { key: 'name', label: 'Location' },
      { key: 'code', label: 'Code' },
      { key: 'city', label: 'City' },
      { key: 'countryCode', label: 'Country' },
      { key: 'isActive', label: 'Status', type: 'status' },
    ],
    fields: [
      { key: 'name', label: 'Location name', type: 'text', required: true },
      { key: 'code', label: 'Code', type: 'text', required: true },
      { key: 'address', label: 'Address', type: 'textarea' },
      { key: 'city', label: 'City', type: 'text' },
      { key: 'countryCode', label: 'Country code', type: 'text', placeholder: 'IN' },
    ],
  },
];

export const MODULES: Record<string, ModuleDefinition> = {
  self: {
    key: 'self',
    title: 'My services',
    eyebrow: 'Employee self-service',
    icon: 'person',
    description:
      'Manage your own leave, timesheets, expenses, learning, reviews, assets, documents and payslips.',
    views: [
      {
        label: 'Leave',
        endpoint: '/me/leave',
        listShape: 'paged',
        createEndpoint: '/me/leave',
        createLabel: 'Request leave',
        columns: [
          { key: 'leaveTypeId', label: 'Leave type' },
          { key: 'startsOn', label: 'Starts', type: 'date' },
          { key: 'endsOn', label: 'Ends', type: 'date' },
          { key: 'days', label: 'Days', type: 'number' },
          { key: 'reason', label: 'Reason' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          {
            key: 'leaveTypeId',
            label: 'Leave type',
            type: 'select',
            required: true,
            optionsEndpoint: '/me/leave-types',
            optionLabel: 'name',
            optionValue: 'id',
          },
          { key: 'startsOn', label: 'Start date', type: 'date', required: true },
          { key: 'endsOn', label: 'End date', type: 'date', required: true },
          { key: 'days', label: 'Number of days', type: 'number', required: true, min: 0 },
          { key: 'reason', label: 'Reason', type: 'textarea', required: true },
        ],
        filters: [
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            options: options('Pending', 'Approved', 'Rejected', 'Cancelled'),
          },
        ],
      },
      {
        label: 'Leave balances',
        endpoint: '/me/leave-balances',
        listShape: 'array',
        columns: [
          { key: 'leaveTypeId', label: 'Leave type' },
          { key: 'year', label: 'Year', type: 'number' },
          { key: 'entitled', label: 'Entitled', type: 'number' },
          { key: 'used', label: 'Used', type: 'number' },
          { key: 'pending', label: 'Pending', type: 'number' },
          { key: 'available', label: 'Available', type: 'number' },
        ],
        filters: [{ key: 'year', label: 'Year', type: 'number' }],
      },
      {
        label: 'Timesheets',
        endpoint: '/me/timesheets',
        listShape: 'paged',
        createEndpoint: '/me/timesheets',
        createLabel: 'Add timesheet',
        columns: [
          { key: 'workDate', label: 'Work date', type: 'date' },
          { key: 'projectCode', label: 'Project' },
          { key: 'description', label: 'Description' },
          { key: 'hours', label: 'Hours', type: 'number' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          { key: 'workDate', label: 'Work date', type: 'date', required: true },
          { key: 'projectCode', label: 'Project code', type: 'text' },
          { key: 'description', label: 'Work description', type: 'textarea', required: true },
          { key: 'hours', label: 'Hours', type: 'number', required: true, min: 0 },
        ],
        filters: [
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            options: options('Pending', 'Approved', 'Rejected', 'Cancelled'),
          },
        ],
      },
      {
        label: 'Expenses',
        endpoint: '/me/expenses',
        listShape: 'paged',
        createEndpoint: '/me/expenses',
        createLabel: 'Create expense',
        columns: [
          { key: 'claimNumber', label: 'Claim' },
          { key: 'category', label: 'Category' },
          { key: 'expenseDate', label: 'Expense date', type: 'date' },
          { key: 'amount', label: 'Amount', type: 'currency' },
          { key: 'description', label: 'Description' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          {
            key: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: options('Travel', 'Meals', 'Office', 'Training', 'Other'),
          },
          { key: 'expenseDate', label: 'Expense date', type: 'date', required: true },
          { key: 'amount', label: 'Amount', type: 'number', required: true, min: 0 },
          {
            key: 'currency',
            label: 'Currency',
            type: 'select',
            required: true,
            options: currencies,
            defaultValue: 'INR',
          },
          { key: 'description', label: 'Description', type: 'textarea', required: true },
          { key: 'receiptStorageKey', label: 'Receipt reference', type: 'text' },
        ],
        filters: [
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            options: options('Draft', 'Submitted', 'Approved', 'Rejected', 'Reimbursed'),
          },
        ],
        rowActions: [
          {
            label: 'Submit for approval',
            icon: 'send',
            method: 'post',
            path: '/me/expenses/{id}/submit?version={version}',
            confirm: 'Submit this expense for approval?',
            visibleStatuses: ['Draft'],
          },
        ],
      },
      {
        label: 'Learning',
        endpoint: '/me/training',
        listShape: 'array',
        columns: [
          { key: 'courseId', label: 'Course' },
          { key: 'status', label: 'Status', type: 'status' },
          { key: 'enrolledAt', label: 'Enrolled', type: 'date' },
          { key: 'completedAt', label: 'Completed', type: 'date' },
          { key: 'score', label: 'Score', type: 'number' },
        ],
        rowActions: [
          {
            label: 'Mark complete',
            icon: 'task_alt',
            method: 'put',
            path: '/me/training/{id}/complete',
            fields: [{ key: 'score', label: 'Score', type: 'number', min: 0 }, versionField],
            visibleStatuses: ['Enrolled', 'InProgress'],
          },
        ],
      },
      {
        label: 'Performance',
        endpoint: '/me/performance',
        listShape: 'array',
        columns: [
          { key: 'cycleId', label: 'Review cycle' },
          { key: 'reviewerId', label: 'Reviewer' },
          { key: 'status', label: 'Status', type: 'status' },
          { key: 'selfRating', label: 'Self rating', type: 'number' },
          { key: 'managerRating', label: 'Manager rating', type: 'number' },
          { key: 'feedback', label: 'Feedback' },
        ],
        rowActions: [
          {
            label: 'Submit self review',
            icon: 'rate_review',
            method: 'put',
            path: '/me/performance/{id}',
            fields: [
              {
                key: 'status',
                label: 'Status',
                type: 'select',
                required: true,
                options: options('SelfReview'),
                defaultValue: 'SelfReview',
              },
              {
                key: 'selfRating',
                label: 'Self rating',
                type: 'number',
                min: 0,
                sourceKey: 'selfRating',
              },
              {
                key: 'managerRating',
                label: 'Manager rating',
                type: 'number',
                sourceKey: 'managerRating',
              },
              {
                key: 'feedback',
                label: 'Self assessment',
                type: 'textarea',
                sourceKey: 'feedback',
              },
              versionField,
            ],
          },
        ],
      },
      {
        label: 'My assets',
        endpoint: '/me/assets',
        listShape: 'array',
        columns: [
          { key: 'assetTag', label: 'Asset tag' },
          { key: 'name', label: 'Asset' },
          { key: 'category', label: 'Category' },
          { key: 'serialNumber', label: 'Serial number' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
      },
      {
        label: 'Documents',
        endpoint: '/me/documents',
        listShape: 'array',
        columns: [
          { key: 'documentType', label: 'Document type' },
          { key: 'fileName', label: 'File' },
          { key: 'contentType', label: 'Content type' },
          { key: 'expiresOn', label: 'Expires', type: 'date' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
      },
      {
        label: 'Payslips',
        endpoint: '/me/payslips',
        listShape: 'array',
        columns: [
          { key: 'runName', label: 'Pay period' },
          { key: 'periodStart', label: 'From', type: 'date' },
          { key: 'periodEnd', label: 'To', type: 'date' },
          { key: 'paymentDate', label: 'Payment date', type: 'date' },
          { key: 'grossPay', label: 'Gross pay', type: 'currency' },
          { key: 'deductions', label: 'Deductions', type: 'currency' },
          { key: 'netPay', label: 'Net pay', type: 'currency' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
      },
      {
        label: 'Announcements',
        endpoint: '/me/announcements',
        listShape: 'array',
        columns: [
          { key: 'title', label: 'Title' },
          { key: 'body', label: 'Message' },
          { key: 'audience', label: 'Audience' },
          { key: 'publishedAt', label: 'Published', type: 'date' },
          { key: 'expiresAt', label: 'Expires', type: 'date' },
        ],
      },
    ],
    highlights: metrics([
      ['Privacy', 'Self only', 'API-enforced ownership', 'green'],
      ['Attendance', 'Location-aware', 'Consent on every clock event', 'blue'],
      ['Approvals', 'Tracked', 'Version-safe workflows', 'amber'],
      ['Access', 'Role-based', 'No admin data exposure', 'violet'],
    ]),
  },
  team: {
    key: 'team',
    title: 'My team',
    eyebrow: 'Manager workspace',
    icon: 'groups',
    description: 'View only your direct reports and approve their operational requests.',
    views: [
      {
        label: 'Direct reports',
        endpoint: '/me/team',
        listShape: 'array',
        columns: [
          { key: 'employeeNumber', label: 'Employee ID' },
          { key: 'fullName', label: 'Employee' },
          { key: 'workEmail', label: 'Email' },
          { key: 'departmentId', label: 'Department' },
          { key: 'designationId', label: 'Designation' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
      },
      {
        label: 'Leave approvals',
        endpoint: '/me/team/leave',
        listShape: 'paged',
        columns: [
          { key: 'employeeId', label: 'Employee' },
          { key: 'startsOn', label: 'Starts', type: 'date' },
          { key: 'endsOn', label: 'Ends', type: 'date' },
          { key: 'days', label: 'Days', type: 'number' },
          { key: 'reason', label: 'Reason' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        filters: [
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            options: options('Pending', 'Approved', 'Rejected', 'Cancelled'),
          },
        ],
        rowActions: [
          {
            label: 'Review leave',
            icon: 'approval',
            method: 'put',
            path: '/me/team/leave/{id}/review',
            fields: [...approveFields, { key: 'comment', label: 'Comment', type: 'textarea' }],
            visibleStatuses: ['Pending'],
          },
        ],
      },
      {
        label: 'Attendance',
        endpoint: '/me/team/attendance',
        listShape: 'paged',
        columns: [
          { key: 'employeeId', label: 'Employee' },
          { key: 'workDate', label: 'Work date', type: 'date' },
          { key: 'clockedInAt', label: 'Clock in', type: 'date' },
          { key: 'clockInAddress', label: 'Clock-in location' },
          { key: 'clockInIpAddress', label: 'Clock-in IP' },
          { key: 'clockedOutAt', label: 'Clock out', type: 'date' },
          { key: 'clockOutAddress', label: 'Clock-out location' },
          { key: 'clockOutIpAddress', label: 'Clock-out IP' },
          { key: 'workHours', label: 'Hours', type: 'number' },
        ],
        filters: [
          { key: 'from', label: 'From', type: 'date' },
          { key: 'to', label: 'To', type: 'date' },
        ],
      },
      {
        label: 'Timesheet approvals',
        endpoint: '/me/team/timesheets',
        listShape: 'paged',
        columns: [
          { key: 'employeeId', label: 'Employee' },
          { key: 'workDate', label: 'Work date', type: 'date' },
          { key: 'projectCode', label: 'Project' },
          { key: 'description', label: 'Description' },
          { key: 'hours', label: 'Hours', type: 'number' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        filters: [
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            options: options('Pending', 'Approved', 'Rejected'),
          },
        ],
        rowActions: [
          {
            label: 'Review timesheet',
            icon: 'fact_check',
            method: 'put',
            path: '/me/team/timesheets/{id}/review',
            fields: approveFields,
            visibleStatuses: ['Pending'],
          },
        ],
      },
      {
        label: 'Expense approvals',
        endpoint: '/me/team/expenses',
        listShape: 'paged',
        columns: [
          { key: 'employeeId', label: 'Employee' },
          { key: 'claimNumber', label: 'Claim' },
          { key: 'category', label: 'Category' },
          { key: 'expenseDate', label: 'Date', type: 'date' },
          { key: 'amount', label: 'Amount', type: 'currency' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        filters: [
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            options: options('Submitted', 'Approved', 'Rejected'),
          },
        ],
        rowActions: [
          {
            label: 'Review expense',
            icon: 'approval',
            method: 'put',
            path: '/me/team/expenses/{id}/review',
            fields: approveFields,
            visibleStatuses: ['Submitted'],
          },
        ],
      },
      {
        label: 'Performance reviews',
        endpoint: '/me/team/performance',
        listShape: 'array',
        columns: [
          { key: 'employeeId', label: 'Employee' },
          { key: 'cycleId', label: 'Cycle' },
          { key: 'selfRating', label: 'Self rating', type: 'number' },
          { key: 'managerRating', label: 'Manager rating', type: 'number' },
          { key: 'feedback', label: 'Feedback' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        rowActions: [
          {
            label: 'Complete manager review',
            icon: 'rate_review',
            method: 'put',
            path: '/me/team/performance/{id}',
            fields: [
              {
                key: 'status',
                label: 'Status',
                type: 'select',
                required: true,
                options: options('ManagerReview', 'Completed'),
                defaultValue: 'ManagerReview',
              },
              { key: 'selfRating', label: 'Self rating', type: 'number', sourceKey: 'selfRating' },
              {
                key: 'managerRating',
                label: 'Manager rating',
                type: 'number',
                min: 0,
                sourceKey: 'managerRating',
              },
              {
                key: 'feedback',
                label: 'Manager feedback',
                type: 'textarea',
                sourceKey: 'feedback',
              },
              versionField,
            ],
          },
        ],
      },
    ],
    highlights: metrics([
      ['Scope', 'Direct reports', 'No wider employee access', 'green'],
      ['Approvals', '3 workflows', 'Leave, time and expenses', 'blue'],
      ['Attendance', 'Location visible', 'Clock-in and clock-out', 'violet'],
      ['Security', 'Server enforced', 'Manager claim and relationship', 'amber'],
    ]),
  },
  platform: {
    key: 'platform',
    title: 'Customer companies',
    eyebrow: 'Platform administration',
    icon: 'domain',
    description:
      'Provision and monitor isolated customer workspaces, subscriptions and employee capacity.',
    views: [
      {
        label: 'Tenants',
        endpoint: '/platform/tenants',
        listShape: 'paged',
        createEndpoint: '/platform/tenants',
        createLabel: 'Create company',
        columns: [
          { key: 'name', label: 'Company' },
          { key: 'slug', label: 'Workspace' },
          { key: 'status', label: 'Status', type: 'status' },
          { key: 'defaultCurrency', label: 'Currency' },
          { key: 'timeZone', label: 'Time zone' },
          { key: 'employeeLimit', label: 'Employee limit', type: 'number' },
        ],
        fields: [
          { key: 'name', label: 'Company name', type: 'text', required: true },
          {
            key: 'slug',
            label: 'Workspace slug',
            type: 'text',
            required: true,
            placeholder: 'acme-india',
          },
          { key: 'adminName', label: 'Administrator name', type: 'text', required: true },
          { key: 'adminEmail', label: 'Administrator email', type: 'email', required: true },
          {
            key: 'adminPassword',
            label: 'Temporary password',
            type: 'password',
            required: true,
            help: 'Use at least 12 characters.',
          },
          {
            key: 'defaultCurrency',
            label: 'Currency',
            type: 'select',
            required: true,
            options: currencies,
            defaultValue: 'INR',
          },
          {
            key: 'timeZone',
            label: 'Time zone',
            type: 'select',
            required: true,
            options: options(
              'Asia/Kolkata',
              'Asia/Singapore',
              'UTC',
              'Europe/London',
              'America/New_York',
            ),
            defaultValue: 'Asia/Kolkata',
          },
          {
            key: 'employeeLimit',
            label: 'Employee limit',
            type: 'number',
            required: true,
            min: 1,
            defaultValue: 50,
          },
        ],
      },
    ],
    highlights: metrics([
      ['Active customers', 'Live', 'Tenant isolation enabled', 'green'],
      ['Trial period', '30 days', 'Applied automatically', 'blue'],
      ['Security', 'JWT + RBAC', 'Per-tenant authorization', 'violet'],
      ['Provisioning', 'Automated', 'Admin and leave defaults', 'amber'],
    ]),
  },
  organization: {
    key: 'organization',
    title: 'Organization',
    eyebrow: 'Core HR · Structure',
    icon: 'account_tree',
    description:
      'Model departments, designations and operating locations with reusable employee selectors.',
    views: organizationViews,
    highlights: metrics([
      ['Structure', '3 layers', 'Departments, roles, locations', 'blue'],
      ['Configuration', 'Live', 'Used across HR workflows', 'green'],
      ['Data isolation', 'Tenant', 'Scoped automatically', 'violet'],
      ['Setup', 'Required', 'Complete before employees', 'amber'],
    ]),
  },
  leave: {
    key: 'leave',
    title: 'Leave management',
    eyebrow: 'Workforce · Time away',
    icon: 'beach_access',
    description: 'Manage leave requests, balances, policies and approval decisions.',
    views: [
      {
        label: 'Requests',
        endpoint: '/leave/requests',
        listShape: 'paged',
        createEndpoint: '/leave/requests',
        createLabel: 'New leave request',
        columns: [
          { key: 'employeeId', label: 'Employee' },
          { key: 'leaveTypeId', label: 'Leave type' },
          { key: 'startsOn', label: 'Starts', type: 'date' },
          { key: 'endsOn', label: 'Ends', type: 'date' },
          { key: 'days', label: 'Days', type: 'number' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          employeeField(),
          {
            key: 'leaveTypeId',
            label: 'Leave type',
            type: 'select',
            required: true,
            ...leaveTypes,
          },
          { key: 'startsOn', label: 'Start date', type: 'date', required: true },
          { key: 'endsOn', label: 'End date', type: 'date', required: true },
          { key: 'days', label: 'Number of days', type: 'number', required: true, min: 0 },
          { key: 'reason', label: 'Reason', type: 'textarea', required: true },
        ],
        filters: [
          { key: 'employeeId', label: 'Employee', type: 'select', ...employees },
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            options: options('Pending', 'Approved', 'Rejected', 'Cancelled'),
          },
        ],
        rowActions: [
          {
            label: 'Review request',
            icon: 'approval',
            method: 'put',
            path: '/leave/requests/{id}/review',
            fields: [
              ...approveFields,
              { key: 'comment', label: 'Review comment', type: 'textarea' },
            ],
            visibleStatuses: ['Pending'],
          },
          {
            label: 'View leave balances',
            icon: 'account_balance_wallet',
            method: 'get',
            path: '/leave/balances/{employeeId}',
            detailTitle: 'Employee leave balances',
            detailColumns: [
              { key: 'year', label: 'Year' },
              { key: 'entitled', label: 'Entitled', type: 'number' },
              { key: 'used', label: 'Used', type: 'number' },
              { key: 'pending', label: 'Pending', type: 'number' },
              { key: 'available', label: 'Available', type: 'number' },
            ],
          },
        ],
      },
      {
        label: 'Leave types',
        endpoint: '/leave/types',
        listShape: 'array',
        createEndpoint: '/leave/types',
        createLabel: 'Create leave type',
        columns: [
          { key: 'name', label: 'Leave type' },
          { key: 'code', label: 'Code' },
          { key: 'annualAllowance', label: 'Allowance', type: 'number' },
          { key: 'isPaid', label: 'Paid', type: 'status' },
          { key: 'requiresDocument', label: 'Document required', type: 'status' },
          { key: 'maxConsecutiveDays', label: 'Maximum stretch', type: 'number' },
        ],
        fields: [
          { key: 'name', label: 'Name', type: 'text', required: true },
          { key: 'code', label: 'Code', type: 'text', required: true },
          {
            key: 'annualAllowance',
            label: 'Annual allowance',
            type: 'number',
            required: true,
            min: 0,
          },
          { key: 'isPaid', label: 'Paid leave', type: 'checkbox', defaultValue: true },
          { key: 'requiresDocument', label: 'Requires document', type: 'checkbox' },
          {
            key: 'maxConsecutiveDays',
            label: 'Maximum consecutive days',
            type: 'number',
            defaultValue: 0,
          },
        ],
      },
      {
        label: 'Balances',
        endpoint: '/leave/balances/{employeeId}',
        listShape: 'array',
        columns: [
          { key: 'leaveTypeId', label: 'Leave type' },
          { key: 'year', label: 'Year', type: 'number' },
          { key: 'entitled', label: 'Entitled', type: 'number' },
          { key: 'used', label: 'Used', type: 'number' },
          { key: 'pending', label: 'Pending', type: 'number' },
          { key: 'available', label: 'Available', type: 'number' },
        ],
        filters: [
          { key: 'employeeId', label: 'Employee', type: 'select', ...employees },
          { key: 'year', label: 'Year', type: 'number' },
        ],
        emptyMessage: 'Select an employee to view leave balances.',
      },
    ],
    highlights: metrics([
      ['Requests', 'Live', 'Employee submission', 'blue'],
      ['Approvals', 'Controlled', 'Version-safe review', 'amber'],
      ['Balances', 'Calculated', 'Available by employee', 'green'],
      ['Policies', 'Flexible', 'Tenant leave types', 'violet'],
    ]),
  },
  attendance: {
    key: 'attendance',
    title: 'Attendance',
    eyebrow: 'Workforce · Time & presence',
    icon: 'schedule',
    description: 'Clock employees in and out and review attendance for a chosen period.',
    views: [
      {
        label: 'Attendance records',
        endpoint: '/attendance',
        listShape: 'paged',
        createEndpoint: '/attendance/clock-in',
        createLabel: 'Clock in',
        columns: [
          { key: 'employeeId', label: 'Employee' },
          { key: 'workDate', label: 'Work date', type: 'date' },
          { key: 'clockedInAt', label: 'Clock in', type: 'date' },
          { key: 'clockInAddress', label: 'Clock-in coordinates' },
          { key: 'clockInIpAddress', label: 'Clock-in IP' },
          { key: 'clockInUserAgent', label: 'Clock-in device' },
          { key: 'clockedOutAt', label: 'Clock out', type: 'date' },
          { key: 'clockOutAddress', label: 'Clock-out coordinates' },
          { key: 'clockOutIpAddress', label: 'Clock-out IP' },
          { key: 'clockOutUserAgent', label: 'Clock-out device' },
          { key: 'workHours', label: 'Hours', type: 'number' },
          { key: 'overtimeHours', label: 'Overtime', type: 'number' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          employeeField(),
          { key: 'timestamp', label: 'Timestamp', type: 'datetime-local' },
          {
            key: 'source',
            label: 'Source',
            type: 'select',
            options: options('web', 'mobile', 'kiosk'),
            defaultValue: 'web',
          },
          { key: 'notes', label: 'Notes', type: 'textarea' },
        ],
        filters: [
          { key: 'employeeId', label: 'Employee', type: 'select', ...employees },
          { key: 'from', label: 'From', type: 'date' },
          { key: 'to', label: 'To', type: 'date' },
        ],
        rowActions: [
          {
            label: 'Clock out employee',
            icon: 'logout',
            method: 'post',
            path: '/attendance/clock-out',
            fields: [
              employeeField('employeeId', 'Employee'),
              { key: 'timestamp', label: 'Timestamp', type: 'datetime-local' },
              {
                key: 'source',
                label: 'Source',
                type: 'select',
                options: options('web', 'mobile', 'kiosk'),
                defaultValue: 'web',
              },
              { key: 'notes', label: 'Notes', type: 'textarea' },
            ],
          },
        ],
      },
    ],
    highlights: metrics([
      ['Time capture', 'Live', 'Web, mobile or kiosk', 'green'],
      ['Overtime', 'Calculated', 'From clock events', 'violet'],
      ['Filtering', 'Flexible', 'Employee and date range', 'blue'],
      ['Integrity', 'Tracked', 'Tenant-scoped records', 'amber'],
    ]),
  },
  workforce: {
    key: 'workforce',
    title: 'Workforce operations',
    eyebrow: 'Workforce · Planning',
    icon: 'calendar_month',
    description: 'Coordinate timesheets, schedules, holidays, documents and announcements.',
    views: [
      {
        label: 'Timesheets',
        endpoint: '/workforce/timesheets',
        listShape: 'paged',
        createEndpoint: '/workforce/timesheets',
        createLabel: 'Submit timesheet',
        columns: [
          { key: 'employeeId', label: 'Employee' },
          { key: 'workDate', label: 'Work date', type: 'date' },
          { key: 'projectCode', label: 'Project' },
          { key: 'description', label: 'Description' },
          { key: 'hours', label: 'Hours', type: 'number' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          employeeField(),
          { key: 'workDate', label: 'Work date', type: 'date', required: true },
          { key: 'projectCode', label: 'Project code', type: 'text' },
          { key: 'description', label: 'Description', type: 'textarea', required: true },
          { key: 'hours', label: 'Hours', type: 'number', required: true, min: 0 },
        ],
        filters: [
          { key: 'employeeId', label: 'Employee', type: 'select', ...employees },
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            options: options('Pending', 'Approved', 'Rejected', 'Cancelled'),
          },
        ],
        rowActions: [
          {
            label: 'Review timesheet',
            icon: 'fact_check',
            method: 'put',
            path: '/workforce/timesheets/{id}/review',
            fields: approveFields,
            visibleStatuses: ['Pending'],
          },
          {
            label: 'Employee documents',
            icon: 'folder',
            method: 'get',
            path: '/workforce/employees/{employeeId}/documents',
            detailTitle: 'Employee documents',
            detailColumns: [
              { key: 'documentType', label: 'Document type' },
              { key: 'fileName', label: 'File' },
              { key: 'expiresOn', label: 'Expires', type: 'date' },
              { key: 'status', label: 'Status', type: 'status' },
            ],
          },
          {
            label: 'Add employee document',
            icon: 'upload_file',
            method: 'post',
            path: '/workforce/documents',
            fields: [
              employeeField(),
              { key: 'documentType', label: 'Document type', type: 'text', required: true },
              { key: 'fileName', label: 'File name', type: 'text', required: true },
              { key: 'storageKey', label: 'Storage key', type: 'text', required: true },
              { key: 'contentType', label: 'Content type', type: 'text' },
              { key: 'expiresOn', label: 'Expiry date', type: 'date' },
            ],
          },
        ],
      },
      {
        label: 'Shifts',
        endpoint: '/workforce/shifts',
        listShape: 'array',
        createEndpoint: '/workforce/shifts',
        createLabel: 'Create shift',
        columns: [
          { key: 'name', label: 'Shift' },
          { key: 'startsAt', label: 'Starts' },
          { key: 'endsAt', label: 'Ends' },
          { key: 'graceMinutes', label: 'Grace minutes', type: 'number' },
          { key: 'isNightShift', label: 'Night shift', type: 'status' },
        ],
        fields: [
          { key: 'name', label: 'Shift name', type: 'text', required: true },
          { key: 'startsAt', label: 'Starts at', type: 'time', required: true },
          { key: 'endsAt', label: 'Ends at', type: 'time', required: true },
          { key: 'graceMinutes', label: 'Grace minutes', type: 'number', defaultValue: 0 },
          { key: 'isNightShift', label: 'Night shift', type: 'checkbox' },
        ],
      },
      {
        label: 'Holidays',
        endpoint: '/workforce/holidays',
        listShape: 'array',
        createEndpoint: '/workforce/holidays',
        createLabel: 'Add holiday',
        columns: [
          { key: 'name', label: 'Holiday' },
          { key: 'date', label: 'Date', type: 'date' },
          { key: 'locationId', label: 'Location' },
          { key: 'isOptional', label: 'Optional', type: 'status' },
        ],
        fields: [
          { key: 'name', label: 'Holiday name', type: 'text', required: true },
          { key: 'date', label: 'Date', type: 'date', required: true },
          { key: 'locationId', label: 'Location', type: 'select', ...locations },
          { key: 'isOptional', label: 'Optional holiday', type: 'checkbox' },
        ],
        filters: [{ key: 'year', label: 'Year', type: 'number' }],
      },
      {
        label: 'Announcements',
        endpoint: '/workforce/announcements',
        listShape: 'array',
        createEndpoint: '/workforce/announcements',
        createLabel: 'Publish announcement',
        columns: [
          { key: 'title', label: 'Title' },
          { key: 'body', label: 'Message' },
          { key: 'audience', label: 'Audience' },
          { key: 'publishedAt', label: 'Published', type: 'date' },
          { key: 'expiresAt', label: 'Expires', type: 'date' },
        ],
        fields: [
          { key: 'title', label: 'Title', type: 'text', required: true },
          { key: 'body', label: 'Message', type: 'textarea', required: true },
          {
            key: 'audience',
            label: 'Audience',
            type: 'select',
            options: options('all', 'employees', 'managers'),
            defaultValue: 'all',
          },
          { key: 'expiresAt', label: 'Expires at', type: 'datetime-local' },
        ],
      },
      {
        label: 'Documents',
        endpoint: '/workforce/employees/{employeeId}/documents',
        listShape: 'array',
        createEndpoint: '/workforce/documents',
        createLabel: 'Add document',
        columns: [
          { key: 'documentType', label: 'Document type' },
          { key: 'fileName', label: 'File' },
          { key: 'contentType', label: 'Content type' },
          { key: 'expiresOn', label: 'Expires', type: 'date' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          employeeField(),
          { key: 'documentType', label: 'Document type', type: 'text', required: true },
          { key: 'fileName', label: 'File name', type: 'text', required: true },
          { key: 'storageKey', label: 'Storage key', type: 'text', required: true },
          { key: 'contentType', label: 'Content type', type: 'text' },
          { key: 'expiresOn', label: 'Expires on', type: 'date' },
        ],
        filters: [{ key: 'employeeId', label: 'Employee', type: 'select', ...employees }],
        emptyMessage: 'Select an employee to view documents.',
        rowActions: [
          {
            label: 'Verify document',
            icon: 'verified',
            method: 'put',
            path: '/workforce/documents/{id}/verify',
            fields: [
              {
                key: 'status',
                label: 'Verification status',
                type: 'select',
                required: true,
                options: options('Pending', 'Verified', 'Rejected', 'Expired'),
                sourceKey: 'status',
              },
              versionField,
            ],
          },
        ],
      },
    ],
    highlights: metrics([
      ['Timesheets', 'Workflow', 'Submit and approve', 'blue'],
      ['Schedules', 'Reusable', 'Shift definitions', 'violet'],
      ['Documents', 'Verified', 'Employee records', 'green'],
      ['Communication', 'Targeted', 'Announcements', 'amber'],
    ]),
  },
  payroll: {
    key: 'payroll',
    title: 'Payroll',
    eyebrow: 'Compensation · Pay runs',
    icon: 'payments',
    description: 'Create, calculate, approve and pay controlled payroll runs.',
    views: [
      {
        label: 'Pay runs',
        endpoint: '/payroll/runs',
        listShape: 'paged',
        createEndpoint: '/payroll/runs',
        createLabel: 'Create payroll run',
        columns: [
          { key: 'name', label: 'Payroll run' },
          { key: 'periodStart', label: 'Period start', type: 'date' },
          { key: 'periodEnd', label: 'Period end', type: 'date' },
          { key: 'paymentDate', label: 'Payment date', type: 'date' },
          { key: 'grossTotal', label: 'Gross', type: 'currency' },
          { key: 'netTotal', label: 'Net', type: 'currency' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          { key: 'name', label: 'Run name', type: 'text', required: true },
          { key: 'periodStart', label: 'Period start', type: 'date', required: true },
          { key: 'periodEnd', label: 'Period end', type: 'date', required: true },
          { key: 'paymentDate', label: 'Payment date', type: 'date', required: true },
          {
            key: 'currency',
            label: 'Currency',
            type: 'select',
            required: true,
            options: currencies,
            defaultValue: 'INR',
          },
        ],
        rowActions: [
          {
            label: 'Calculate payroll',
            icon: 'calculate',
            method: 'post',
            path: '/payroll/runs/{id}/calculate',
            confirm: 'Calculate this payroll from current employee salaries?',
          },
          {
            label: 'Change status',
            icon: 'published_with_changes',
            method: 'put',
            path: '/payroll/runs/{id}/status?status={statusValue}&version={version}',
            fields: [
              {
                key: 'statusValue',
                label: 'New status',
                type: 'select',
                required: true,
                options: options('Draft', 'Processing', 'Approved', 'Paid', 'Cancelled'),
              },
              versionField,
            ],
          },
          {
            label: 'View payroll items',
            icon: 'receipt_long',
            method: 'get',
            path: '/payroll/runs/{id}/items',
            detailTitle: 'Payroll items',
            detailColumns: [
              { key: 'employeeId', label: 'Employee' },
              { key: 'basicPay', label: 'Basic pay', type: 'currency' },
              { key: 'allowances', label: 'Allowances', type: 'currency' },
              { key: 'deductions', label: 'Deductions', type: 'currency' },
              { key: 'taxes', label: 'Taxes', type: 'currency' },
              { key: 'netPay', label: 'Net pay', type: 'currency' },
            ],
          },
        ],
      },
    ],
    highlights: metrics([
      ['Lifecycle', '5 stages', 'Draft through paid', 'blue'],
      ['Calculation', 'Automated', 'Current active employees', 'green'],
      ['Concurrency', 'Protected', 'Version-safe approvals', 'violet'],
      ['Auditability', 'Complete', 'Every status transition', 'amber'],
    ]),
  },
  recruitment: {
    key: 'recruitment',
    title: 'Recruitment',
    eyebrow: 'Talent · Hiring pipeline',
    icon: 'person_search',
    description:
      'Create openings, register candidates and move applications through hiring stages.',
    views: [
      {
        label: 'Job openings',
        endpoint: '/recruitment/jobs',
        listShape: 'array',
        createEndpoint: '/recruitment/jobs',
        createLabel: 'Create opening',
        columns: [
          { key: 'title', label: 'Job title' },
          { key: 'code', label: 'Job code' },
          { key: 'openings', label: 'Openings', type: 'number' },
          { key: 'closesOn', label: 'Closes', type: 'date' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          { key: 'title', label: 'Job title', type: 'text', required: true },
          { key: 'code', label: 'Job code', type: 'text', required: true },
          { key: 'description', label: 'Description', type: 'textarea', required: true },
          { key: 'departmentId', label: 'Department', type: 'select', ...departments },
          { key: 'hiringManagerId', label: 'Hiring manager', type: 'select', ...employees },
          { key: 'openings', label: 'Openings', type: 'number', required: true, defaultValue: 1 },
          { key: 'closesOn', label: 'Closing date', type: 'date' },
        ],
        filters: [
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            options: options('Draft', 'Open', 'OnHold', 'Closed', 'Cancelled'),
          },
        ],
        toolbarActions: [
          {
            label: 'Register candidate',
            icon: 'person_add',
            method: 'post',
            path: '/recruitment/candidates',
            fields: [
              { key: 'firstName', label: 'First name', type: 'text', required: true },
              { key: 'lastName', label: 'Last name', type: 'text', required: true },
              { key: 'email', label: 'Email', type: 'email', required: true },
              { key: 'phone', label: 'Phone', type: 'text' },
              { key: 'resumeStorageKey', label: 'Resume storage key', type: 'text' },
              { key: 'source', label: 'Source', type: 'text' },
            ],
          },
        ],
        rowActions: [
          {
            label: 'View applications',
            icon: 'groups',
            method: 'get',
            path: '/recruitment/jobs/{id}/applications',
            detailTitle: 'Job applications',
            detailColumns: [
              { key: 'candidateId', label: 'Candidate' },
              { key: 'stage', label: 'Stage', type: 'status' },
              { key: 'rating', label: 'Rating', type: 'number' },
              { key: 'notes', label: 'Notes' },
              { key: 'appliedAt', label: 'Applied', type: 'date' },
            ],
          },
          {
            label: 'Add candidate application',
            icon: 'how_to_reg',
            method: 'post',
            path: '/recruitment/applications',
            fields: [
              {
                key: 'jobOpeningId',
                label: 'Job opening',
                type: 'text',
                required: true,
                sourceKey: 'id',
              },
              {
                key: 'candidateId',
                label: 'Candidate ID',
                type: 'text',
                required: true,
                help: 'Use the ID shown after registering a candidate.',
              },
            ],
          },
        ],
      },
      {
        label: 'Applications',
        endpoint: '/recruitment/jobs/{jobId}/applications',
        listShape: 'array',
        columns: [
          { key: 'candidateId', label: 'Candidate ID' },
          { key: 'stage', label: 'Stage', type: 'status' },
          { key: 'rating', label: 'Rating', type: 'number' },
          { key: 'notes', label: 'Notes' },
          { key: 'appliedAt', label: 'Applied at', type: 'date' },
        ],
        filters: [
          {
            key: 'jobId',
            label: 'Job opening',
            type: 'select',
            optionsEndpoint: '/recruitment/jobs',
            optionLabel: 'title',
            optionValue: 'id',
          },
        ],
        emptyMessage: 'Select a job opening to view its application pipeline.',
        rowActions: [
          {
            label: 'Move candidate',
            icon: 'move_up',
            method: 'put',
            path: '/recruitment/applications/{id}/stage',
            fields: [
              {
                key: 'stage',
                label: 'Pipeline stage',
                type: 'select',
                required: true,
                options: options(
                  'Applied',
                  'Screening',
                  'Interview',
                  'Offer',
                  'Hired',
                  'Rejected',
                  'Withdrawn',
                ),
                sourceKey: 'stage',
              },
              { key: 'rating', label: 'Rating', type: 'number', min: 0, sourceKey: 'rating' },
              { key: 'notes', label: 'Notes', type: 'textarea', sourceKey: 'notes' },
            ],
          },
        ],
      },
    ],
    highlights: metrics([
      ['Openings', 'Structured', 'Department and manager linked', 'blue'],
      ['Candidates', 'Centralized', 'Source and resume tracked', 'green'],
      ['Pipeline', '7 stages', 'Applied through hired', 'violet'],
      ['Feedback', 'Captured', 'Ratings and notes', 'amber'],
    ]),
  },
  performance: {
    key: 'performance',
    title: 'Performance',
    eyebrow: 'Talent · Growth',
    icon: 'monitoring',
    description: 'Run review cycles, collect ratings and progress reviews through completion.',
    views: [
      {
        label: 'Reviews',
        endpoint: '/performance/reviews',
        listShape: 'array',
        createEndpoint: '/performance/reviews',
        createLabel: 'Create review',
        columns: [
          { key: 'employeeId', label: 'Employee' },
          { key: 'reviewerId', label: 'Reviewer' },
          { key: 'cycleId', label: 'Cycle' },
          { key: 'selfRating', label: 'Self rating', type: 'number' },
          { key: 'managerRating', label: 'Manager rating', type: 'number' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          {
            key: 'cycleId',
            label: 'Cycle ID',
            type: 'text',
            required: true,
            help: 'Create a cycle first and copy the returned ID.',
          },
          employeeField(),
          employeeField('reviewerId', 'Reviewer'),
          {
            key: 'goalsJson',
            label: 'Goals JSON',
            type: 'textarea',
            placeholder: '[{"goal":"Increase retention","weight":40}]',
          },
        ],
        filters: [
          { key: 'employeeId', label: 'Employee', type: 'select', ...employees },
          { key: 'cycleId', label: 'Cycle ID', type: 'text' },
        ],
        toolbarActions: [
          {
            label: 'Create review cycle',
            icon: 'event_repeat',
            method: 'post',
            path: '/performance/cycles',
            fields: [
              { key: 'name', label: 'Cycle name', type: 'text', required: true },
              { key: 'startsOn', label: 'Start date', type: 'date', required: true },
              { key: 'endsOn', label: 'End date', type: 'date', required: true },
            ],
          },
        ],
        rowActions: [
          {
            label: 'Update review',
            icon: 'rate_review',
            method: 'put',
            path: '/performance/reviews/{id}',
            fields: [
              {
                key: 'status',
                label: 'Status',
                type: 'select',
                required: true,
                options: options(
                  'Draft',
                  'SelfReview',
                  'ManagerReview',
                  'Calibration',
                  'Completed',
                ),
                sourceKey: 'status',
              },
              { key: 'selfRating', label: 'Self rating', type: 'number', sourceKey: 'selfRating' },
              {
                key: 'managerRating',
                label: 'Manager rating',
                type: 'number',
                sourceKey: 'managerRating',
              },
              { key: 'feedback', label: 'Feedback', type: 'textarea', sourceKey: 'feedback' },
              versionField,
            ],
          },
        ],
      },
    ],
    highlights: metrics([
      ['Cycles', 'Flexible', 'Date-bounded programmes', 'blue'],
      ['Reviews', 'Role-based', 'HR creates, users update', 'green'],
      ['Ratings', 'Balanced', 'Self and manager', 'violet'],
      ['Workflow', '5 stages', 'Draft to complete', 'amber'],
    ]),
  },
  assets: {
    key: 'assets',
    title: 'Asset management',
    eyebrow: 'Operations · Equipment',
    icon: 'laptop_mac',
    description: 'Track company equipment and employee custody.',
    views: [
      {
        label: 'Assets',
        endpoint: '/assets',
        listShape: 'array',
        createEndpoint: '/assets',
        createLabel: 'Register asset',
        columns: [
          { key: 'assetTag', label: 'Asset tag' },
          { key: 'name', label: 'Asset' },
          { key: 'category', label: 'Category' },
          { key: 'serialNumber', label: 'Serial number' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          { key: 'assetTag', label: 'Asset tag', type: 'text', required: true },
          { key: 'name', label: 'Asset name', type: 'text', required: true },
          {
            key: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: options('Laptop', 'Mobile', 'Monitor', 'Accessory', 'Security'),
          },
          { key: 'serialNumber', label: 'Serial number', type: 'text' },
          { key: 'purchasedOn', label: 'Purchase date', type: 'date' },
          { key: 'purchaseCost', label: 'Purchase cost', type: 'number', min: 0 },
        ],
        filters: [
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            options: options('Available', 'Assigned', 'Maintenance', 'Retired', 'Lost'),
          },
        ],
        rowActions: [
          {
            label: 'Assign to employee',
            icon: 'assignment_ind',
            method: 'post',
            path: '/assets/{id}/assign',
            fields: [
              employeeField(),
              { key: 'notes', label: 'Assignment notes', type: 'textarea' },
            ],
            visibleStatuses: ['Available'],
          },
          {
            label: 'Return asset',
            icon: 'assignment_return',
            method: 'post',
            path: '/assets/{id}/return',
            confirm: 'Return this asset and make it available?',
            visibleStatuses: ['Assigned'],
          },
        ],
      },
    ],
    highlights: metrics([
      ['Inventory', 'Centralized', 'Tags and serial numbers', 'blue'],
      ['Custody', 'Traceable', 'Employee assignments', 'green'],
      ['Lifecycle', '5 states', 'Available through retired', 'violet'],
      ['Controls', 'HR managed', 'Protected operations', 'amber'],
    ]),
  },
  expenses: {
    key: 'expenses',
    title: 'Expenses',
    eyebrow: 'Compensation · Reimbursements',
    icon: 'receipt_long',
    description: 'Submit, approve and track employee expense claims.',
    views: [
      {
        label: 'Claims',
        endpoint: '/expenses',
        listShape: 'paged',
        createEndpoint: '/expenses',
        createLabel: 'New expense claim',
        columns: [
          { key: 'claimNumber', label: 'Claim number' },
          { key: 'employeeId', label: 'Employee' },
          { key: 'category', label: 'Category' },
          { key: 'expenseDate', label: 'Expense date', type: 'date' },
          { key: 'amount', label: 'Amount', type: 'currency' },
          { key: 'status', label: 'Status', type: 'status' },
        ],
        fields: [
          employeeField(),
          {
            key: 'category',
            label: 'Category',
            type: 'select',
            required: true,
            options: options('Travel', 'Meals', 'Office', 'Training', 'Other'),
          },
          { key: 'expenseDate', label: 'Expense date', type: 'date', required: true },
          { key: 'amount', label: 'Amount', type: 'number', required: true, min: 0 },
          {
            key: 'currency',
            label: 'Currency',
            type: 'select',
            required: true,
            options: currencies,
            defaultValue: 'INR',
          },
          { key: 'description', label: 'Description', type: 'textarea', required: true },
          { key: 'receiptStorageKey', label: 'Receipt storage key', type: 'text' },
        ],
        filters: [
          { key: 'employeeId', label: 'Employee', type: 'select', ...employees },
          {
            key: 'status',
            label: 'Status',
            type: 'select',
            options: options('Draft', 'Submitted', 'Approved', 'Rejected', 'Reimbursed'),
          },
        ],
        rowActions: [
          {
            label: 'Submit claim',
            icon: 'send',
            method: 'post',
            path: '/expenses/{id}/submit?version={version}',
            confirm: 'Submit this claim for approval?',
            visibleStatuses: ['Draft'],
          },
          {
            label: 'Review claim',
            icon: 'approval',
            method: 'put',
            path: '/expenses/{id}/review',
            fields: approveFields,
            visibleStatuses: ['Submitted'],
          },
        ],
      },
    ],
    highlights: metrics([
      ['Claims', 'Employee-led', 'Create and submit', 'blue'],
      ['Approvals', 'Version-safe', 'Approve or reject', 'green'],
      ['Receipts', 'Referenced', 'Storage-ready design', 'violet'],
      ['Status', '5 stages', 'Draft to reimbursed', 'amber'],
    ]),
  },
  training: {
    key: 'training',
    title: 'Learning & development',
    eyebrow: 'Talent · Capability',
    icon: 'school',
    description: 'Build courses, enroll employees and record completion scores.',
    views: [
      {
        label: 'Courses',
        endpoint: '/training/courses',
        listShape: 'array',
        createEndpoint: '/training/courses',
        createLabel: 'Create course',
        columns: [
          { key: 'title', label: 'Course' },
          { key: 'provider', label: 'Provider' },
          { key: 'durationHours', label: 'Duration', type: 'number' },
          { key: 'isMandatory', label: 'Mandatory', type: 'status' },
          { key: 'expiresOn', label: 'Expires', type: 'date' },
        ],
        fields: [
          { key: 'title', label: 'Course title', type: 'text', required: true },
          { key: 'provider', label: 'Provider', type: 'text' },
          { key: 'description', label: 'Description', type: 'textarea' },
          { key: 'durationHours', label: 'Duration hours', type: 'number', required: true, min: 0 },
          { key: 'isMandatory', label: 'Mandatory course', type: 'checkbox' },
          { key: 'expiresOn', label: 'Expires on', type: 'date' },
        ],
        rowActions: [
          {
            label: 'Enroll employee',
            icon: 'person_add',
            method: 'post',
            path: '/training/courses/{id}/enroll',
            fields: [employeeField()],
          },
        ],
      },
      {
        label: 'Enrollments',
        endpoint: '/training/enrollments',
        listShape: 'array',
        columns: [
          { key: 'courseId', label: 'Course' },
          { key: 'employeeId', label: 'Employee' },
          { key: 'status', label: 'Status', type: 'status' },
          { key: 'enrolledAt', label: 'Enrolled', type: 'date' },
          { key: 'completedAt', label: 'Completed', type: 'date' },
          { key: 'score', label: 'Score', type: 'number' },
        ],
        filters: [{ key: 'employeeId', label: 'Employee', type: 'select', ...employees }],
        rowActions: [
          {
            label: 'Complete training',
            icon: 'task_alt',
            method: 'put',
            path: '/training/enrollments/{id}/complete',
            fields: [{ key: 'score', label: 'Score', type: 'number', min: 0 }, versionField],
            visibleStatuses: ['Enrolled', 'InProgress'],
          },
        ],
      },
    ],
    highlights: metrics([
      ['Catalog', 'Reusable', 'Provider and duration', 'blue'],
      ['Enrollment', 'Tracked', 'Employee learning history', 'green'],
      ['Compliance', 'Mandatory', 'Expiry support', 'violet'],
      ['Results', 'Measured', 'Completion scores', 'amber'],
    ]),
  },
  identity: {
    key: 'identity',
    title: 'Access & roles',
    eyebrow: 'Administration · Security',
    icon: 'admin_panel_settings',
    description: 'Control tenant users, role assignments and permission boundaries.',
    views: [
      {
        label: 'Users',
        endpoint: '/identity/users',
        listShape: 'paged',
        createEndpoint: '/identity/users',
        createLabel: 'Create user',
        columns: [
          { key: 'displayName', label: 'User' },
          { key: 'email', label: 'Email' },
          { key: 'employeeId', label: 'Linked employee' },
          { key: 'roleIds', label: 'Assigned roles' },
          { key: 'isActive', label: 'Status', type: 'status' },
          { key: 'version', label: 'Version', type: 'number' },
        ],
        fields: [
          {
            key: 'employeeId',
            label: 'Employee account',
            type: 'select',
            optionsEndpoint: '/employees?page=1&pageSize=200',
            optionsShape: 'paged',
            optionLabel: 'fullName',
            optionValue: 'id',
            help: 'Link normal users to their employee record. Platform and service accounts may remain unlinked.',
          },
          { key: 'displayName', label: 'Display name', type: 'text', required: true },
          {
            key: 'email',
            label: 'Email',
            type: 'email',
            required: true,
            help: 'For linked employees, this must match the work email.',
          },
          { key: 'password', label: 'Temporary password', type: 'password', required: true },
          { key: 'roleIds', label: 'Roles', type: 'multiselect', required: true, ...roles },
        ],
        rowActions: [
          {
            label: 'Change roles',
            icon: 'manage_accounts',
            method: 'put',
            path: '/identity/users/{id}/roles',
            fields: [
              {
                key: 'roleIds',
                label: 'Roles',
                type: 'multiselect',
                required: true,
                ...roles,
                sourceKey: 'roleIds',
              },
              versionField,
            ],
          },
        ],
      },
      {
        label: 'Roles',
        endpoint: '/identity/roles',
        listShape: 'array',
        createEndpoint: '/identity/roles',
        createLabel: 'Create role',
        columns: [
          { key: 'name', label: 'Role' },
          { key: 'permissions', label: 'Permissions' },
          { key: 'isSystem', label: 'System role', type: 'status' },
        ],
        fields: [
          { key: 'name', label: 'Role name', type: 'text', required: true },
          {
            key: 'permissions',
            label: 'Permissions',
            type: 'multiselect',
            required: true,
            options: [
              { label: 'All tenant permissions', value: '*' },
              { label: 'Admin dashboard', value: 'dashboard.admin' },
              { label: 'Read employees', value: 'employees.read' },
              { label: 'Manage employees', value: 'employees.manage' },
              { label: 'Manage organization', value: 'organization.manage' },
              { label: 'Manage leave', value: 'leave.manage' },
              { label: 'Manage attendance', value: 'attendance.manage' },
              { label: 'Manage workforce', value: 'workforce.manage' },
              { label: 'Manage payroll', value: 'payroll.manage' },
              { label: 'Manage recruitment', value: 'recruitment.manage' },
              { label: 'Manage performance', value: 'performance.manage' },
              { label: 'Manage assets', value: 'assets.manage' },
              { label: 'Manage expenses', value: 'expenses.manage' },
              { label: 'Manage training', value: 'training.manage' },
              { label: 'Manage users and roles', value: 'identity.manage' },
              { label: 'Read audit logs', value: 'audit.read' },
              { label: 'Employee self-service', value: 'self.service' },
              { label: 'Read direct reports', value: 'team.read' },
              { label: 'Approve direct-report requests', value: 'team.approve' },
            ],
          },
        ],
      },
    ],
    highlights: metrics([
      ['Authorization', 'RBAC', 'Roles and permissions', 'blue'],
      ['Isolation', 'Tenant', 'No cross-company access', 'green'],
      ['Passwords', 'PBKDF2', 'Secure server hashing', 'violet'],
      ['Changes', 'Protected', 'Version-safe role updates', 'amber'],
    ]),
  },
  audit: {
    key: 'audit',
    title: 'Audit log',
    eyebrow: 'Administration · Governance',
    icon: 'history',
    description:
      'Review immutable activity history for sensitive data and administrative operations.',
    views: [
      {
        label: 'All activity',
        endpoint: '/audit-logs',
        listShape: 'paged',
        columns: [
          { key: 'createdAt', label: 'Timestamp', type: 'date' },
          { key: 'actorUserId', label: 'Actor' },
          { key: 'action', label: 'Action', type: 'status' },
          { key: 'entityType', label: 'Entity type' },
          { key: 'entityId', label: 'Entity ID' },
          { key: 'ipAddress', label: 'IP address' },
          { key: 'correlationId', label: 'Correlation ID' },
        ],
        filters: [{ key: 'entityType', label: 'Entity type', type: 'text' }],
      },
    ],
    highlights: metrics([
      ['Coverage', 'Automatic', 'Changes captured centrally', 'blue'],
      ['Traceability', 'Correlation IDs', 'Request-level investigation', 'green'],
      ['Actors', 'Identified', 'User and IP information', 'violet'],
      ['Governance', 'Tenant-scoped', 'Secure audit access', 'amber'],
    ]),
  },
};
